/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.device_booster.createQODSession.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RequestIpv4Address
 */

public class RequestIpv4Address {
  @JsonProperty("privateAddress")
  private String privateAddress = null;

  @JsonProperty("publicPort")
  private String publicPort = null;

  @JsonProperty("publicAddress")
  private String publicAddress = null;

  public RequestIpv4Address privateAddress(String privateAddress) {
    this.privateAddress = privateAddress;
    return this;
  }

   /**
   * Get privateAddress
   * @return privateAddress
  **/
  public String getPrivateAddress() {
    return privateAddress;
  }

  public void setPrivateAddress(String privateAddress) {
    this.privateAddress = privateAddress;
  }

  public RequestIpv4Address publicPort(String publicPort) {
    this.publicPort = publicPort;
    return this;
  }

   /**
   * Get publicPort
   * @return publicPort
  **/
  public String getPublicPort() {
    return publicPort;
  }

  public void setPublicPort(String publicPort) {
    this.publicPort = publicPort;
  }

  public RequestIpv4Address publicAddress(String publicAddress) {
    this.publicAddress = publicAddress;
    return this;
  }

   /**
   * Get publicAddress
   * @return publicAddress
  **/
  public String getPublicAddress() {
    return publicAddress;
  }

  public void setPublicAddress(String publicAddress) {
    this.publicAddress = publicAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestIpv4Address Request_ipv4Address = (RequestIpv4Address) o;
    return Objects.equals(this.privateAddress, Request_ipv4Address.privateAddress) &&
        Objects.equals(this.publicPort, Request_ipv4Address.publicPort) &&
        Objects.equals(this.publicAddress, Request_ipv4Address.publicAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(privateAddress, publicPort, publicAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestIpv4Address {\n");
    
    sb.append("    privateAddress: ").append(toIndentedString(privateAddress)).append("\n");
    sb.append("    publicPort: ").append(toIndentedString(publicPort)).append("\n");
    sb.append("    publicAddress: ").append(toIndentedString(publicAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
