/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.device_booster.createQODSession.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RequestWebhook
 */

public class RequestWebhook {
  @JsonProperty("notificationUrl")
  private String notificationUrl = null;

  @JsonProperty("notificationAuthToken")
  private String notificationAuthToken = null;

  public RequestWebhook notificationUrl(String notificationUrl) {
    this.notificationUrl = notificationUrl;
    return this;
  }

   /**
   * Get notificationUrl
   * @return notificationUrl
  **/
  public String getNotificationUrl() {
    return notificationUrl;
  }

  public void setNotificationUrl(String notificationUrl) {
    this.notificationUrl = notificationUrl;
  }

  public RequestWebhook notificationAuthToken(String notificationAuthToken) {
    this.notificationAuthToken = notificationAuthToken;
    return this;
  }

   /**
   * Get notificationAuthToken
   * @return notificationAuthToken
  **/
  public String getNotificationAuthToken() {
    return notificationAuthToken;
  }

  public void setNotificationAuthToken(String notificationAuthToken) {
    this.notificationAuthToken = notificationAuthToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestWebhook Request_webhook = (RequestWebhook) o;
    return Objects.equals(this.notificationUrl, Request_webhook.notificationUrl) &&
        Objects.equals(this.notificationAuthToken, Request_webhook.notificationAuthToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notificationUrl, notificationAuthToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestWebhook {\n");
    
    sb.append("    notificationUrl: ").append(toIndentedString(notificationUrl)).append("\n");
    sb.append("    notificationAuthToken: ").append(toIndentedString(notificationAuthToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
