/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.device_booster.createQODSession.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.device_booster.createQODSession.model.RequestRanges;
/**
 * RequestDevicePorts
 */

public class RequestDevicePorts {
  @JsonProperty("ranges")
  private RequestRanges ranges = null;

  @JsonProperty("ports")
  private String ports = null;

  public RequestDevicePorts ranges(RequestRanges ranges) {
    this.ranges = ranges;
    return this;
  }

   /**
   * Get ranges
   * @return ranges
  **/
  public RequestRanges getRanges() {
    return ranges;
  }

  public void setRanges(RequestRanges ranges) {
    this.ranges = ranges;
  }

  public RequestDevicePorts ports(String ports) {
    this.ports = ports;
    return this;
  }

   /**
   * Get ports
   * @return ports
  **/
  public String getPorts() {
    return ports;
  }

  public void setPorts(String ports) {
    this.ports = ports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestDevicePorts Request_devicePorts = (RequestDevicePorts) o;
    return Objects.equals(this.ranges, Request_devicePorts.ranges) &&
        Objects.equals(this.ports, Request_devicePorts.ports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ranges, ports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestDevicePorts {\n");
    
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("    ports: ").append(toIndentedString(ports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
