/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wavemaker.device_booster.createQODSession.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wavemaker.device_booster.createQODSession.model.RequestApplicationServer;
import com.wavemaker.device_booster.createQODSession.model.RequestApplicationServerPorts;
import com.wavemaker.device_booster.createQODSession.model.RequestDevice;
import com.wavemaker.device_booster.createQODSession.model.RequestDevicePorts;
import com.wavemaker.device_booster.createQODSession.model.RequestWebhook;
/**
 * RootRequest
 */

public class RootRequest {
  @JsonProperty("notificationUrl")
  private String notificationUrl = null;

  @JsonProperty("duration")
  private Integer duration = null;

  @JsonProperty("qosProfile")
  private String qosProfile = null;

  @JsonProperty("webhook")
  private RequestWebhook webhook = null;

  @JsonProperty("applicationServer")
  private RequestApplicationServer applicationServer = null;

  @JsonProperty("notificationAuthToken")
  private String notificationAuthToken = null;

  @JsonProperty("applicationServerPorts")
  private RequestApplicationServerPorts applicationServerPorts = null;

  @JsonProperty("device")
  private RequestDevice device = null;

  @JsonProperty("devicePorts")
  private RequestDevicePorts devicePorts = null;

  public RootRequest notificationUrl(String notificationUrl) {
    this.notificationUrl = notificationUrl;
    return this;
  }

   /**
   * Get notificationUrl
   * @return notificationUrl
  **/
  public String getNotificationUrl() {
    return notificationUrl;
  }

  public void setNotificationUrl(String notificationUrl) {
    this.notificationUrl = notificationUrl;
  }

  public RootRequest duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public RootRequest qosProfile(String qosProfile) {
    this.qosProfile = qosProfile;
    return this;
  }

   /**
   * Get qosProfile
   * @return qosProfile
  **/
  public String getQosProfile() {
    return qosProfile;
  }

  public void setQosProfile(String qosProfile) {
    this.qosProfile = qosProfile;
  }

  public RootRequest webhook(RequestWebhook webhook) {
    this.webhook = webhook;
    return this;
  }

   /**
   * Get webhook
   * @return webhook
  **/
  public RequestWebhook getWebhook() {
    return webhook;
  }

  public void setWebhook(RequestWebhook webhook) {
    this.webhook = webhook;
  }

  public RootRequest applicationServer(RequestApplicationServer applicationServer) {
    this.applicationServer = applicationServer;
    return this;
  }

   /**
   * Get applicationServer
   * @return applicationServer
  **/
  public RequestApplicationServer getApplicationServer() {
    return applicationServer;
  }

  public void setApplicationServer(RequestApplicationServer applicationServer) {
    this.applicationServer = applicationServer;
  }

  public RootRequest notificationAuthToken(String notificationAuthToken) {
    this.notificationAuthToken = notificationAuthToken;
    return this;
  }

   /**
   * Get notificationAuthToken
   * @return notificationAuthToken
  **/
  public String getNotificationAuthToken() {
    return notificationAuthToken;
  }

  public void setNotificationAuthToken(String notificationAuthToken) {
    this.notificationAuthToken = notificationAuthToken;
  }

  public RootRequest applicationServerPorts(RequestApplicationServerPorts applicationServerPorts) {
    this.applicationServerPorts = applicationServerPorts;
    return this;
  }

   /**
   * Get applicationServerPorts
   * @return applicationServerPorts
  **/
  public RequestApplicationServerPorts getApplicationServerPorts() {
    return applicationServerPorts;
  }

  public void setApplicationServerPorts(RequestApplicationServerPorts applicationServerPorts) {
    this.applicationServerPorts = applicationServerPorts;
  }

  public RootRequest device(RequestDevice device) {
    this.device = device;
    return this;
  }

   /**
   * Get device
   * @return device
  **/
  public RequestDevice getDevice() {
    return device;
  }

  public void setDevice(RequestDevice device) {
    this.device = device;
  }

  public RootRequest devicePorts(RequestDevicePorts devicePorts) {
    this.devicePorts = devicePorts;
    return this;
  }

   /**
   * Get devicePorts
   * @return devicePorts
  **/
  public RequestDevicePorts getDevicePorts() {
    return devicePorts;
  }

  public void setDevicePorts(RequestDevicePorts devicePorts) {
    this.devicePorts = devicePorts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootRequest RootRequest = (RootRequest) o;
    return Objects.equals(this.notificationUrl, RootRequest.notificationUrl) &&
        Objects.equals(this.duration, RootRequest.duration) &&
        Objects.equals(this.qosProfile, RootRequest.qosProfile) &&
        Objects.equals(this.webhook, RootRequest.webhook) &&
        Objects.equals(this.applicationServer, RootRequest.applicationServer) &&
        Objects.equals(this.notificationAuthToken, RootRequest.notificationAuthToken) &&
        Objects.equals(this.applicationServerPorts, RootRequest.applicationServerPorts) &&
        Objects.equals(this.device, RootRequest.device) &&
        Objects.equals(this.devicePorts, RootRequest.devicePorts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notificationUrl, duration, qosProfile, webhook, applicationServer, notificationAuthToken, applicationServerPorts, device, devicePorts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootRequest {\n");
    
    sb.append("    notificationUrl: ").append(toIndentedString(notificationUrl)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    qosProfile: ").append(toIndentedString(qosProfile)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("    applicationServer: ").append(toIndentedString(applicationServer)).append("\n");
    sb.append("    notificationAuthToken: ").append(toIndentedString(notificationAuthToken)).append("\n");
    sb.append("    applicationServerPorts: ").append(toIndentedString(applicationServerPorts)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    devicePorts: ").append(toIndentedString(devicePorts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
